Develop2 -- GUI stuff for sprint 2
EngineTeam/laker-polling pull request #18
Opened 2017-03-15 21:57 UTC by mcavatai

I hope I did this right.

2017-03-15 22:10 UTC, jregistr requested changes
Everything looks fine. I've two comments. Just 2 things that need to be deleted from your repository.

2017-03-15 22:10 UTC, jregistr commented on classes/production/laker-polling/application.groovy
> +server {
Delete this file from your repository. It's in the git ignore. but since it's on the repo, it's still part of the merge.

2017-03-15 22:10 UTC, jregistr commented on classes/production/laker-polling/application.yml
> +---
Delete the classes folder from your repo. It should be getting ignored but it looks like this repo didn't initially have the .gitignore file in it.

2017-03-15 22:36 UTC, jregistr approved these changes

2017-03-15 22:36 UTC, merged

2017-03-16 03:48 UTC, mcavatai commented
Added a dashboard interface with the following functionality:

- Student can view classes they are enrolled in upon logging in.
     - Currently this information is displayed via bootstrap data, but will eventually refer to
        information set by instructors in sprint 3.
- Student can log out using the logout button in the top right.